{
 "title": "CCU-1",
 "tags": [ "ccu" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccu_power_active{job=\"ccu-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccu_power_voltage{job=\"ccu-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccu_battery_charge{job=\"ccu-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccu_battery_state{job=\"ccu-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccu_balance{job=\"ccu-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccu_signal_percent{job=\"ccu-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signal, dBm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccu_signal_dbm{job=\"ccu-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signal Strength",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccu_signal_strength{job=\"ccu-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inputs Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ccu_temp{job=\"ccu-1\"}",
     "legendFormat": "CCU-825"
    },
    {
     "expr": "ccu_in1_temp{job=\"ccu-1\"}",
     "legendFormat": "1. TEMP_IN"
    },
    {
     "expr": "ccu_in2_temp{job=\"ccu-1\"}",
     "legendFormat": "2. TEMP_HEAT"
    },
    {
     "expr": "ccu_in3_temp{job=\"ccu-1\"}",
     "legendFormat": "3. TEMP_OUT"
    },
    {
     "expr": "ccu_in4_temp{job=\"ccu-1\"}",
     "legendFormat": "4. TEMP_CELLAR"
    },
    {
     "expr": "ccu_in5_temp{job=\"ccu-1\"}",
     "legendFormat": "5. TEMP_WELL"
    },
    {
     "expr": "ccu_in6_temp{job=\"ccu-1\"}",
     "legendFormat": "6. TEMP_SEPTIC"
    }
   ]
  },
  {
   "title": "Inputs Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "ccu_in7_active{job=\"ccu-1\"}",
     "legendFormat": "SENSOR7"
    },
    {
     "expr": "ccu_in8_active{job=\"ccu-1\"}",
     "legendFormat": "SENSOR8"
    },
    {
     "expr": "ccu_in9_active{job=\"ccu-1\"}",
     "legendFormat": "MOTION_KITCHEN"
    },
    {
     "expr": "ccu_in10_active{job=\"ccu-1\"}",
     "legendFormat": "SENSOR10"
    },
    {
     "expr": "ccu_in11_active{job=\"ccu-1\"}",
     "legendFormat": "SENSOR11"
    },
    {
     "expr": "ccu_in12_active{job=\"ccu-1\"}",
     "legendFormat": "SENSOR12"
    },
    {
     "expr": "ccu_in13_active{job=\"ccu-1\"}",
     "legendFormat": "SENSOR13"
    },
    {
     "expr": "ccu_in14_active{job=\"ccu-1\"}",
     "legendFormat": "SENSOR14"
    },
    {
     "expr": "ccu_in15_active{job=\"ccu-1\"}",
     "legendFormat": "HERCON_TAMBOUR"
    },
    {
     "expr": "ccu_in16_active{job=\"ccu-1\"}",
     "legendFormat": "HERCON_KITCHEN"
    }
   ]
  },
  {
   "title": "Outputs Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "ccu_out1_active{job=\"ccu-1\"}",
     "legendFormat": "RELAY1"
    },
    {
     "expr": "ccu_out2_active{job=\"ccu-1\"}",
     "legendFormat": "RELAY2"
    },
    {
     "expr": "ccu_out3_active{job=\"ccu-1\"}",
     "legendFormat": "LAMP"
    },
    {
     "expr": "ccu_out4_active{job=\"ccu-1\"}",
     "legendFormat": "HORN_SMALL"
    },
    {
     "expr": "ccu_out5_active{job=\"ccu-1\"}",
     "legendFormat": "HORN_BIG"
    },
    {
     "expr": "ccu_out6_active{job=\"ccu-1\"}",
     "legendFormat": "OUT4"
    },
    {
     "expr": "ccu_out7_active{job=\"ccu-1\"}",
     "legendFormat": "OUT5"
    }
   ]
  }
 ]
}